# Generated by Django 5.0.1 on 2024-03-02 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProperty',
            fields=[
                ('property_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('apartment_building', 'Apartment Building'), ('single_family_home', 'Single Family Home'), ('condominium', 'Condominium'), ('duplex', 'Duplex')], default='apartment_building', max_length=50)),
                ('total_units', models.IntegerField(default=1)),
                ('property_size', models.IntegerField(blank=True, help_text='Size of the property in square feet', null=True)),
                ('building_age', models.IntegerField(blank=True, help_text='Age of the building in years', null=True)),
                ('management_company', models.CharField(blank=True, max_length=100, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('utilities', models.TextField(blank=True, null=True)),
                ('maintenance_services', models.TextField(blank=True, null=True)),
                ('parking', models.TextField(blank=True, null=True)),
                ('security_features', models.TextField(blank=True, null=True)),
                ('rules_regulations', models.TextField(blank=True, null=True)),
                ('accessibility', models.TextField(blank=True, null=True)),
                ('lease_terms', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'property_information',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unit_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('unit_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('floor_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bedrooms', models.CharField(blank=True, max_length=100, null=True)),
                ('bathrooms', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_size', models.CharField(blank=True, max_length=100, null=True)),
                ('rent_amount', models.IntegerField(blank=True, null=True)),
                ('security_deposit', models.IntegerField(blank=True, null=True)),
                ('availability', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.parentproperty')),
            ],
            options={
                'db_table': 'unit_information',
            },
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('tenants_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.IntegerField(blank=True, help_text='0712345678 or +254712345678', null=True)),
                ('gender', models.CharField(max_length=10)),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField(blank=True, null=True)),
                ('lease_term', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=250, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.units')),
            ],
            options={
                'db_table': 'tenants_information',
            },
        ),
    ]
