# Generated by Django 5.0.1 on 2024-03-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='dob',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
    ]
