# Generated by Django 5.0.1 on 2024-03-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0003_alter_parentproperty_property_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentproperty',
            name='building_age',
            field=models.CharField(blank=True, help_text='Age of the building in years', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='parentproperty',
            name='total_units',
            field=models.CharField(default=1, max_length=250),
        ),
    ]
