# Generated by Django 5.0.1 on 2024-03-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0005_rename_address_parentproperty_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tenants',
            new_name='Tenant',
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
    ]
