# Generated by Django 5.0.1 on 2024-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0006_rename_tenants_tenant_rename_units_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentproperty',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment Building'), ('single_family_home', 'Single Family Home'), ('condominium', 'Condominium'), ('duplex', 'Duplex')], default='apartment', max_length=50),
        ),
    ]
