# Generated by Django 5.0.1 on 2024-03-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0007_alter_parentproperty_property_type'),
        ('main', '0009_remove_customer_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentproperty',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
        migrations.AlterField(
            model_name='parentproperty',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('single_family_home', 'Single Family Home'), ('condominium', 'Condominium'), ('duplex', 'Duplex')], default='apartment', max_length=50),
        ),
    ]
