# Generated by Django 5.0.1 on 2024-03-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0008_parentproperty_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentproperty',
            name='rent_average',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
