# Generated by Django 5.0.1 on 2024-03-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0009_alter_parentproperty_rent_average'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentproperty',
            old_name='rent_average',
            new_name='average_rent',
        ),
    ]
