# Generated by Django 5.0.1 on 2024-04-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0010_rename_rent_average_parentproperty_average_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('parent_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlord.parentproperty')),
            ],
        ),
    ]
