# Generated by Django 5.0.1 on 2024-02-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='classification',
            field=models.CharField(blank=True, default='Customer', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Landlord',
        ),
    ]
